### Reference:
### https://docs.travis-ci.com/user/languages/go/
language: go

sudo: false

go:
  - "1.11.x"
  - master

os:
  - linux

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
