### Reference:
### https://docs.travis-ci.com/user/languages/go/
language: go

sudo: false

go:
  - "1.11.x"
  - master

matrix:
  fast_finish: true
  include:
  - go: "1.11.x"
    env: GO111MODULE=on

os:
  - linux

script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
