### Reference:
### https://docs.travis-ci.com/user/languages/go/
language: go

sudo: false

env:
  - GO111MODULE=on

go:
  - "1.11.x"
  - "master"

os:
  - linux
  - osx
  #- windows

#matrix:
#  fast_finish: true
#  include:
#  - go: "1.11.x"
#    env: GO111MODULE=on
#  - go: "master"
#    env: GO111MODULE=on

script:
  - make go-test-codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
